[package]
name = "nl-sh"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2.7", features = ["derive"] }
home = "0.5.9"
inquire = { git = "https://github.com/mikecvet/inquire.git", branch = "history" }
llama_cpp_rs = "0.3.0"
openai-api-rs = "4.0.7"
regex = "1"
